# Generated by Django 4.1 on 2022-09-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Websites',
            new_name='Website',
        ),
    ]
